export const sCopy = {
  inicio: { es: "Inicio", en: "Inicio" },
  cartilla: { es: "Cartilla", en: "Cartilla" },
  practicaRapida: { es: "Práctica rápida", en: "Práctica rápida" },
  modoRepaso: { es: "Modo repaso", en: "Modo repaso" },
  reiniciarProgreso: { es: "Reiniciar progreso", en: "Reiniciar progreso" },
  reiniciarPregunta: {
    es: "¿Reiniciar tu progreso de las 24 lecciones?",
    en: "¿Reiniciar tu progreso de las 24 lecciones?",
  },
  las24Lecciones: { es: "Las 24 lecciones", en: "Las 24 lecciones" },
  las24LeccionesDe: { es: "Las 24 lecciones de ", en: "Las 24 lecciones de " },
  aprendePaso: {
    es: "Aprende paso a paso, de la lección 1 a la 24. Completa una para desbloquear la siguiente.",
    en: "Aprende paso a paso, de la lección 1 a la 24. Completa una para desbloquear la siguiente.",
  },
  progreso: { es: "Progreso:", en: "Progreso:" },
  leccion: { es: "Lección", en: "Lección" },
  completada: { es: "Completada", en: "Completada" },
  bloqueada: { es: "Bloqueada", en: "Bloqueada" },
  disponible: { es: "Disponible", en: "Disponible" },
  paginas: { es: "Páginas", en: "Páginas" },
  indice: { es: "Índice", en: "Índice" },
  tareaAsignada: { es: "Tarea asignada", en: "Tarea asignada" },
  entrega: { es: "Entrega:", en: "Entrega:" },
  limite: { es: "Límite", en: "Límite" },
  min: { es: "min", en: "min" },
  yaCompletaste: { es: "Ya completaste esta lección", en: "Ya completaste esta lección" },
  anterior: { es: "Anterior", en: "Anterior" },
  terminado: { es: "Terminado", en: "Terminado" },
  marcarTerminar: { es: "Marcar y terminar", en: "Marcar y terminar" },
  siguiente: { es: "Siguiente", en: "Siguiente" },
  marcarSiguiente: { es: "Marcar y siguiente", en: "Marcar y siguiente" },
  conocerasVocales: {
    es: "En esta lección conocerás las cinco vocales del español: a, e, i, o, u.",
    en: "En esta lección conocerás las cinco vocales del español: a, e, i, o, u.",
  },
  silabas: { es: "Sílabas", en: "Sílabas" },
  palabras: { es: "Palabras", en: "Palabras" },
  respuestas: { es: "Respuestas", en: "Respuestas" },
  palabrasConVocal: { es: "Palabras con la vocal", en: "Palabras con la vocal" },
  oir: { es: "oír", en: "oír" },
  palabrasEjemplo: { es: "Palabras de ejemplo", en: "Palabras de ejemplo" },
  oraciones: { es: "Oraciones", en: "Oraciones" },
  cargando: { es: "Cargando…", en: "Cargando…" },
  holaName: { es: "Hola, {name}", en: "Hola, {name}" },
  clase: { es: "Clase:", en: "Clase:" },
  tuCodigo: { es: "Tu código:", en: "Tu código:" },
  lecciones: { es: "Lecciones", en: "Lecciones" },
  ejercicios: { es: "Ejercicios", en: "Ejercicios" },
  tiempo: { es: "Tiempo", en: "Tiempo" },
  insignias: { es: "Insignias", en: "Insignias" },
  teConvieneRepasar: { es: "Te conviene repasar", en: "Te conviene repasar" },
  tuvisteErrores: {
    es: "Tuviste varios errores en estas lecciones. ¡Vuelve a intentarlo!",
    en: "Tuviste varios errores en estas lecciones. ¡Vuelve a intentarlo!",
  },
  irRepaso: { es: "Ir al modo repaso →", en: "Ir al modo repaso →" },
  aciertosPorLeccion: {
    es: "Aciertos por lección (primeras 12)",
    en: "Aciertos por lección (primeras 12)",
  },
  tus24Lecciones: { es: "Tus 24 lecciones", en: "Tus 24 lecciones" },
  pendiente: { es: "pendiente", en: "pendiente" },
  acierto: { es: "acierto", en: "acierto" },
  aprendePasoVocales: {
    es: "Aprende paso a paso, vocal por vocal y consonante por consonante.",
    en: "Aprende paso a paso, vocal por vocal y consonante por consonante.",
  },
  drill: {
    es: "Drill de 60 segundos: identifica sílabas a toda velocidad.",
    en: "Drill de 60 segundos: identifica sílabas a toda velocidad.",
  },
  miProgreso: { es: "Mi progreso", en: "Mi progreso" },
  holaNameRevisa: {
    es: "Hola {name} — revisa tus lecciones, aciertos e insignias.",
    en: "Hola {name} — revisa tus lecciones, aciertos e insignias.",
  },
  practicaLeccionesFallaste: {
    es: "Practica las lecciones donde fallaste y refuerza lo pendiente.",
    en: "Practica las lecciones donde fallaste y refuerza lo pendiente.",
  },
  soyEstudiante: { es: "Soy estudiante", en: "Soy estudiante" },
  uneteClase: {
    es: "Únete a tu clase con el código que te dio tu maestra o maestro.",
    en: "Únete a tu clase con el código que te dio tu maestra o maestro.",
  },
  panelMaestro: { es: "Panel de Maestro", en: "Panel de Maestro" },
  creaClases: {
    es: "Crea clases, agrega alumnos y revisa el progreso real.",
    en: "Crea clases, agrega alumnos y revisa el progreso real.",
  },
  laAutora: { es: "La autora", en: "La autora" },
  conoceAutora: {
    es: "Conoce a Leonor Lopetegui, autora del método.",
    en: "Conoce a Leonor Lopetegui, autora del método.",
  },
  edicionDigital: {
    es: "Edición digital interactiva — método fonético K-2.",
    en: "Edición digital interactiva — método fonético K-2.",
  },
  prefieresLeer: { es: "¿Prefieres leer el libro?", en: "¿Prefieres leer el libro?" },
  abrirLector: { es: "Abrir lector", en: "Abrir lector" },
  // Practica
  drillSilabas: { es: "Drill de sílabas", en: "Drill de sílabas" },
  escuchaToca: {
    es: "Escucha la sílaba y toca la respuesta correcta antes de que se acabe el tiempo.",
    en: "Escucha la sílaba y toca la respuesta correcta antes de que se acabe el tiempo.",
  },
  duracion: { es: "Duración", en: "Duración" },
  s: { es: "s", en: "s" },
  alcance: { es: "Alcance", en: "Alcance" },
  soloDesbloqueadas: { es: "Solo desbloqueadas", en: "Solo desbloqueadas" },
  todasLecciones: { es: "Todas las lecciones", en: "Todas las lecciones" },
  silabasPool: { es: "sílabas en el pool.", en: "sílabas en el pool." },
  empezar: { es: "Empezar", en: "Empezar" },
  reescuchar: { es: "Reescuchar", en: "Reescuchar" },
  tocaSilaba: { es: "Toca la sílaba que escuchas", en: "Toca la sílaba que escuchas" },
  tiempoHecho: { es: "¡Tiempo!", en: "¡Tiempo!" },
  aciertos: { es: "Aciertos", en: "Aciertos" },
  errores: { es: "Errores", en: "Errores" },
  precision: { es: "Precisión", en: "Precisión" },
  otraVez: { es: "Otra vez", en: "Otra vez" },
  volver: { es: "Volver", en: "Volver" },
  // Repaso
  olvidarResultados: {
    es: "¿Olvidar los resultados de tus ejercicios para empezar el repaso de cero?",
    en: "¿Olvidar los resultados de tus ejercicios para empezar el repaso de cero?",
  },
  reiniciarRepaso: { es: "Reiniciar repaso", en: "Reiniciar repaso" },
  practicaFalta: {
    es: "Practica lo que te falta y refuerza lo que fallaste",
    en: "Practica lo que te falta y refuerza lo que fallaste",
  },
  mostramosPrimero: {
    es: "Te mostramos primero las lecciones donde tuviste errores, y después las pendientes.",
    en: "Te mostramos primero las lecciones donde tuviste errores, y después las pendientes.",
  },
  paraReforzar: { es: "Para reforzar", en: "Para reforzar" },
  bienHechoRepaso: {
    es: "¡Bien hecho! No hay ejercicios fallados pendientes de reforzar.",
    en: "¡Bien hecho! No hay ejercicios fallados pendientes de reforzar.",
  },
  pendientes: { es: "Pendientes", en: "Pendientes" },
  hasCompletado: {
    es: "Has completado todas las lecciones disponibles.",
    en: "Has completado todas las lecciones disponibles.",
  },
  // Unirse
  pideleMaestra: {
    es: "Pídele a tu maestra o maestro el código de la clase.",
    en: "Pídele a tu maestra o maestro el código de la clase.",
  },
  estasEnClase: { es: "Estás en la clase", en: "Estás en la clase" },
  continuarLecciones: { es: "Continuar a las lecciones", en: "Continuar a las lecciones" },
  salir: { es: "Salir", en: "Salir" },
  codigoClase: { es: "Código de la clase", en: "Código de la clase" },
  tuCodigoPersonal: { es: "Tu código personal", en: "Tu código personal" },
  entrar: { es: "Entrar", en: "Entrar" },
  elijeTuNombre: { es: "¡Toca tu nombre!", en: "¡Toca tu nombre!" },
  cambiarCodigo: { es: "Cambiar código", en: "Cambiar código" },
  buscandoClase: { es: "Buscando tu clase...", en: "Buscando tu clase..." },
  // Autora
  educadora: { es: "Educadora · Autora · Editora", en: "Educadora · Autora · Editora" },
  bioLeonor: {
    es: "Casi cincuenta años enseñando español en las aulas del Condado de Miami-Dade. Fundadora de Double R Publishing y autora de La Cartilla de Gretel, un método propio —fonético, visual y entrañable— que ha acompañado a miles de familias.",
    en: "Casi cincuenta años enseñando español en las aulas del Condado de Miami-Dade. Fundadora de Double R Publishing y autora de La Cartilla de Gretel, un método propio —fonético, visual y entrañable— que ha acompañado a miles de familias.",
  },
  comprarCartilla: { es: "Comprar la cartilla", en: "Comprar la cartilla" },
  anosAula: { es: "años en el aula", en: "años en el aula" },
  premioCervantes: { es: "Premio Cervantes", en: "Premio Cervantes" },
  anosLiderando: { es: "años liderando bilingüe", en: "años liderando bilingüe" },
  diaLopetegui: { es: "Día de la Sra. Lopetegui", en: "Día de la Sra. Lopetegui" },
  citaLeonor: {
    es: "Enseñar a leer en la lengua materna es regalarle al niño la llave de su propio mundo.",
    en: "Enseñar a leer en la lengua materna es regalarle al niño la llave de su propio mundo.",
  },
  premio1: {
    es: "Premio Cervantes — Nova Southeastern University",
    en: "Premio Cervantes — Nova Southeastern University",
  },
  premio2: {
    es: "Maestra del Año 2001–2002 — James H. Bright Elementary",
    en: "Maestra del Año 2001–2002 — James H. Bright Elementary",
  },
  premio3: {
    es: "Educadora Bilingüe del Año — Florida Bilingual Association",
    en: "Educadora Bilingüe del Año — Florida Bilingual Association",
  },
  premio4: {
    es: "Día de la Sra. Leonor Lopetegui — Sweetwater · 2014",
    en: "Día de la Sra. Leonor Lopetegui — Sweetwater · 2014",
  },
  paraEscuelas: { es: "Para escuelas y familias", en: "Para escuelas y familias" },
  contacto: { es: "Contacto", en: "Contacto" },
};
