export const sCopy = {
  inicio: { es: "Inicio", en: "Home" },
  cartilla: { es: "Cartilla", en: "Workbook" },
  practicaRapida: { es: "Práctica rápida", en: "Quick Practice" },
  modoRepaso: { es: "Modo repaso", en: "Review Mode" },
  reiniciarProgreso: { es: "Reiniciar progreso", en: "Reset Progress" },
  reiniciarPregunta: { es: "¿Reiniciar tu progreso de las 24 lecciones?", en: "Reset your progress for all 24 lessons?" },
  las24Lecciones: { es: "Las 24 lecciones", en: "The 24 lessons" },
  las24LeccionesDe: { es: "Las 24 lecciones de ", en: "The 24 lessons of " },
  aprendePaso: { es: "Aprende paso a paso, de la lección 1 a la 24. Completa una para desbloquear la siguiente.", en: "Learn step by step, from lesson 1 to 24. Complete one to unlock the next." },
  progreso: { es: "Progreso:", en: "Progress:" },
  leccion: { es: "Lección", en: "Lesson" },
  completada: { es: "Completada", en: "Completed" },
  bloqueada: { es: "Bloqueada", en: "Locked" },
  disponible: { es: "Disponible", en: "Available" },
  paginas: { es: "Páginas", en: "Pages" },
  indice: { es: "Índice", en: "Index" },
  tareaAsignada: { es: "Tarea asignada", en: "Assigned task" },
  entrega: { es: "Entrega:", en: "Due:" },
  limite: { es: "Límite", en: "Limit" },
  min: { es: "min", en: "min" },
  yaCompletaste: { es: "Ya completaste esta lección", en: "You have already completed this lesson" },
  anterior: { es: "Anterior", en: "Previous" },
  terminado: { es: "Terminado", en: "Finished" },
  marcarTerminar: { es: "Marcar y terminar", en: "Mark & finish" },
  siguiente: { es: "Siguiente", en: "Next" },
  marcarSiguiente: { es: "Marcar y siguiente", en: "Mark & next" },
  conocerasVocales: { es: "En esta lección conocerás las cinco vocales del español: a, e, i, o, u.", en: "In this lesson you will learn the five Spanish vowels: a, e, i, o, u." },
  silabas: { es: "Sílabas", en: "Syllables" },
  palabras: { es: "Palabras", en: "Words" },
  respuestas: { es: "Respuestas", en: "Answers" },
  palabrasConVocal: { es: "Palabras con la vocal", en: "Words with the vowel" },
  oir: { es: "oír", en: "listen" },
  palabrasEjemplo: { es: "Palabras de ejemplo", en: "Example words" },
  oraciones: { es: "Oraciones", en: "Sentences" },
  cargando: { es: "Cargando…", en: "Loading…" },
  holaName: { es: "Hola, {name}", en: "Hello, {name}" },
  clase: { es: "Clase:", en: "Class:" },
  tuCodigo: { es: "Tu código:", en: "Your code:" },
  lecciones: { es: "Lecciones", en: "Lessons" },
  ejercicios: { es: "Ejercicios", en: "Exercises" },
  tiempo: { es: "Tiempo", en: "Time" },
  insignias: { es: "Insignias", en: "Badges" },
  teConvieneRepasar: { es: "Te conviene repasar", en: "You should review" },
  tuvisteErrores: { es: "Tuviste varios errores en estas lecciones. ¡Vuelve a intentarlo!", en: "You had a few errors in these lessons. Try again!" },
  irRepaso: { es: "Ir al modo repaso →", en: "Go to review mode →" },
  aciertosPorLeccion: { es: "Aciertos por lección (primeras 12)", en: "Accuracy by lesson (first 12)" },
  tus24Lecciones: { es: "Tus 24 lecciones", en: "Your 24 lessons" },
  pendiente: { es: "pendiente", en: "pending" },
  acierto: { es: "acierto", en: "accuracy" },
  aprendePasoVocales: { es: "Aprende paso a paso, vocal por vocal y consonante por consonante.", en: "Learn step by step, vowel by vowel and consonant by consonant." },
  drill: { es: "Drill de 60 segundos: identifica sílabas a toda velocidad.", en: "60-second drill: identify syllables at full speed." },
  miProgreso: { es: "Mi progreso", en: "My progress" },
  holaNameRevisa: { es: "Hola {name} — revisa tus lecciones, aciertos e insignias.", en: "Hello {name} — check your lessons, accuracy and badges." },
  practicaLeccionesFallaste: { es: "Practica las lecciones donde fallaste y refuerza lo pendiente.", en: "Practice the lessons you failed and reinforce pending ones." },
  soyEstudiante: { es: "Soy estudiante", en: "I am a student" },
  uneteClase: { es: "Únete a tu clase con el código que te dio tu maestra o maestro.", en: "Join your class with the code your teacher gave you." },
  panelMaestro: { es: "Panel de Maestro", en: "Teacher Dashboard" },
  creaClases: { es: "Crea clases, agrega alumnos y revisa el progreso real.", en: "Create classes, add students and review real progress." },
  laAutora: { es: "La autora", en: "The author" },
  conoceAutora: { es: "Conoce a Leonor Lopetegui, autora del método.", en: "Meet Leonor Lopetegui, author of the method." },
  edicionDigital: { es: "Edición digital interactiva — método fonético K-2.", en: "Interactive digital edition — K-2 phonetic method." },
  prefieresLeer: { es: "¿Prefieres leer el libro?", en: "Prefer to read the book?" },
  abrirLector: { es: "Abrir lector", en: "Open reader" },
  // Practica
  drillSilabas: { es: "Drill de sílabas", en: "Syllable Drill" },
  escuchaToca: { es: "Escucha la sílaba y toca la respuesta correcta antes de que se acabe el tiempo.", en: "Listen to the syllable and tap the correct answer before time runs out." },
  duracion: { es: "Duración", en: "Duration" },
  s: { es: "s", en: "s" },
  alcance: { es: "Alcance", en: "Scope" },
  soloDesbloqueadas: { es: "Solo desbloqueadas", en: "Only unlocked" },
  todasLecciones: { es: "Todas las lecciones", en: "All lessons" },
  silabasPool: { es: "sílabas en el pool.", en: "syllables in pool." },
  empezar: { es: "Empezar", en: "Start" },
  reescuchar: { es: "Reescuchar", en: "Re-listen" },
  tocaSilaba: { es: "Toca la sílaba que escuchas", en: "Tap the syllable you hear" },
  tiempoHecho: { es: "¡Tiempo!", en: "Time's up!" },
  aciertos: { es: "Aciertos", en: "Hits" },
  errores: { es: "Errores", en: "Misses" },
  precision: { es: "Precisión", en: "Accuracy" },
  otraVez: { es: "Otra vez", en: "Play again" },
  volver: { es: "Volver", en: "Back" },
  // Repaso
  olvidarResultados: { es: "¿Olvidar los resultados de tus ejercicios para empezar el repaso de cero?", en: "Forget your exercise results to start the review from scratch?" },
  reiniciarRepaso: { es: "Reiniciar repaso", en: "Reset review" },
  practicaFalta: { es: "Practica lo que te falta y refuerza lo que fallaste", en: "Practice what you miss and reinforce what you failed" },
  mostramosPrimero: { es: "Te mostramos primero las lecciones donde tuviste errores, y después las pendientes.", en: "We show you the lessons where you made mistakes first, then the pending ones." },
  paraReforzar: { es: "Para reforzar", en: "To reinforce" },
  bienHechoRepaso: { es: "¡Bien hecho! No hay ejercicios fallados pendientes de reforzar.", en: "Well done! No failed exercises to reinforce." },
  pendientes: { es: "Pendientes", en: "Pending" },
  hasCompletado: { es: "Has completado todas las lecciones disponibles.", en: "You have completed all available lessons." },
  // Unirse
  pideleMaestra: { es: "Pídele a tu maestra o maestro los dos códigos.", en: "Ask your teacher for the two codes." },
  estasEnClase: { es: "Estás en la clase", en: "You are in class" },
  continuarLecciones: { es: "Continuar a las lecciones", en: "Continue to lessons" },
  salir: { es: "Salir", en: "Log out" },
  codigoClase: { es: "Código de la clase", en: "Class code" },
  tuCodigoPersonal: { es: "Tu código personal", en: "Your personal code" },
  entrar: { es: "Entrar", en: "Enter" },
  // Autora
  educadora: { es: "Educadora · Autora · Editora", en: "Educator · Author · Editor" },
  bioLeonor: { es: "Casi cincuenta años enseñando español en las aulas del Condado de Miami-Dade. Fundadora de Double R Publishing y autora de La Cartilla de Gretel, un método propio —fonético, visual y entrañable— que ha acompañado a miles de familias.", en: "Almost fifty years teaching Spanish in Miami-Dade County classrooms. Founder of Double R Publishing and author of La Cartilla de Gretel, her own phonics-based method that has accompanied thousands of families." },
  comprarCartilla: { es: "Comprar la cartilla", en: "Buy workbook" },
  anosAula: { es: "años en el aula", en: "years in the classroom" },
  premioCervantes: { es: "Premio Cervantes", en: "Cervantes Award" },
  anosLiderando: { es: "años liderando bilingüe", en: "years leading bilingual ed" },
  diaLopetegui: { es: "Día de la Sra. Lopetegui", en: "Mrs. Lopetegui Day" },
  citaLeonor: { es: "Enseñar a leer en la lengua materna es regalarle al niño la llave de su propio mundo.", en: "Teaching to read in the mother tongue is giving the child the key to their own world." },
  premio1: { es: "Premio Cervantes — Nova Southeastern University", en: "Cervantes Award — Nova Southeastern University" },
  premio2: { es: "Maestra del Año 2001–2002 — James H. Bright Elementary", en: "Teacher of the Year 2001–2002 — James H. Bright Elementary" },
  premio3: { es: "Educadora Bilingüe del Año — Florida Bilingual Association", en: "Bilingual Educator of the Year — Florida Bilingual Association" },
  premio4: { es: "Día de la Sra. Leonor Lopetegui — Sweetwater · 2014", en: "Mrs. Leonor Lopetegui Day — Sweetwater · 2014" },
  paraEscuelas: { es: "Para escuelas y familias", en: "For schools and families" },
  contacto: { es: "Contacto", en: "Contact" },
};
