import manifestData from "./workbook-manifest.json";
import { WorkbookManifestFileSchema, type WorkbookManifestFile } from "./manifest-schema";
import { manifestPageToEnginePage } from "./manifest-adapter";
import type { PhysicalPage } from "./types";

/**
 * The manifest is a real source file (src/content/workbook/workbook-manifest.json,
 * written by scripts/build-workbook-manifest.mjs), so it's statically
 * imported like every other local content JSON in this repo (see
 * src/lib/book-faithful.ts's page-layouts.json import) rather than fetched
 * at runtime — it ships in the bundle and needs a rebuild to pick up a new
 * census, which is the correct tradeoff for content that's regenerated by
 * a script, not edited live.
 *
 * Parsed once through the zod schema so a malformed manifest fails loudly
 * in dev (console.error) instead of silently rendering broken pages —
 * still degrades to an empty manifest rather than throwing, since a
 * partially-invalid census shouldn't crash the whole app.
 */
function parseManifest(): WorkbookManifestFile {
  const result = WorkbookManifestFileSchema.safeParse(manifestData);
  if (!result.success) {
    console.error("workbook-manifest.json failed schema validation:", result.error.issues);
    return { version: "0.0.0-invalid-manifest", pages: [] };
  }
  return result.data;
}

let cached: WorkbookManifestFile | null = null;

export function getWorkbookManifest(): WorkbookManifestFile {
  if (!cached) cached = parseManifest();
  return cached;
}

/**
 * The one function Task 3 asks for: given a real printed page number
 * (1-92), returns that page rendered into the engine's PhysicalPage shape,
 * or null if the census doesn't have that page yet (never invented).
 */
export function getWorkbookPage(physicalPage: number): PhysicalPage | null {
  const manifest = getWorkbookManifest();
  const page = manifest.pages.find((p) => p.physicalPage === physicalPage);
  return page ? manifestPageToEnginePage(page) : null;
}

/** All physicalPage numbers currently present in the manifest, ascending —
 * lets a UI (e.g. the manifest sandbox) offer only pages that actually exist. */
export function listAvailablePhysicalPages(): number[] {
  return getWorkbookManifest()
    .pages.map((p) => p.physicalPage)
    .sort((a, b) => a - b);
}

/** Clears the in-memory parsed-manifest cache — useful for tests. */
export function clearWorkbookManifestCache(): void {
  cached = null;
}
