# Generates src/data/flipchart-source-colors.json from the Flip Chart source (run from repo root: python3 scripts/extract-flipchart-colors.py).
import json,sys

import numpy as np
from PIL import Image
import os
R=os.getcwd()+'/'
fc={}
for f in ['3-22','23-42','43-62']: fc.update(json.load(open(R+f'src/data/flipchart-text-{f}.json')))
def load(p):
    im=Image.open(R+f'public/cartilla/art/hd/flipchart/page-{p:03d}.jpg').convert('RGB')
    im=im.resize((500,int(im.height*500/im.width)))
    return np.asarray(im).astype(float)/255
def hexc(c): return '#%02x%02x%02x'%tuple(int(round(v*255)) for v in c)
def tint_pixels(a,box):
    x0,y0,x1,y1=[int(v/2) for v in box]; px=a[y0:y1,x0:x1].reshape(-1,3)
    mx=px.max(1); mn=px.min(1); s=(mx-mn)/np.maximum(mx,1e-6)
    m=(mx>0.55)&(s>0.06)&(mn>0.3)
    # exclude red/black text: red text = high sat with low green
    m&=~((px[:,0]>0.6)&(px[:,1]<0.3))
    return px[m]
def light_edge(px):
    lum=px.mean(1); o=np.argsort(lum)
    edge=np.median(px[o[:max(1,len(o)//5)]],0); light=np.median(px[o[-max(1,len(o)//3):]],0)
    return hexc(light),hexc(edge)
out={}
lessons={}
t=json.load(open(R+'src/data/teacher-flipchart.json'))['pages']
lesson_of={x['flipchartPage']:x.get('lesson') for x in t}
for p in range(3,63):
    bgs=[i for i in fc.get(str(p),[]) if i.get('backgroundColor') and i['backgroundColor'].lower() not in ('#ffffff','#fff','#000000')]
    rec={}
    if bgs: rec['panel']=max(bgs,key=lambda i:i['width']*i['height'])['backgroundColor'].lower(); rec['panelSource']='pdf-text-layer'
    out[p]=rec
for p in [9]+[12+3*i for i in range(17)]:
    a=load(p); px=tint_pixels(a,(760,20,990,480))
    l,e=light_edge(px); out[p]['crescentLight']=l; out[p]['crescentEdge']=e; out[p]['crescentSource']='hd-scan-sample'
# vowel circles page 3
a=load(3)
vs=[i for i in fc['3'] if i['text'].strip() in list('aeiou') and i['fontSize']>70]
circ=[]
seen=set()
for i in sorted(vs,key=lambda i:i['x']):
    if i['text'].strip() in seen: continue
    seen.add(i['text'].strip())
    cx=i['x']+i['width']/2; cy=i['y']+i['height']/2
    px=tint_pixels(a,(cx-90,cy-90,cx+90,cy+90)); px=px[px.min(1)>0.5]
    if len(px)>20: circ.append({"vowel":i['text'].strip(),"color":light_edge(px)[1]})
out[3]['vowelCircles']=circ
# fill missing panels from the same lesson
for p,rec in out.items():
    if 'panel' in rec: continue
    L=lesson_of.get(p)
    sib=[out[q]['panel'] for q in out if lesson_of.get(q)==L and 'panel' in out[q]]
    if sib: rec['panel']=sib[0]; rec['panelSource']='same-lesson-pdf-text-layer'
    elif 'crescentLight' in rec: rec['panel']=rec['crescentLight']; rec['panelSource']='hd-scan-sample'
    else:
        c=[out[q].get('crescentLight') for q in out if lesson_of.get(q)==L and out[q].get('crescentLight')]
        if c: rec['panel']=c[0]; rec['panelSource']='same-lesson-hd-scan-sample'
data={"_comment":"Per-page colors taken from La Cartilla de Gretel Flip Chart source: panel colors from the PDF text layer (flipchart-text-*.json backgroundColor), crescent/vowel-circle colors sampled from the HD page renders (public/cartilla/art/hd/flipchart). Generated by scripts/extract-flipchart-colors.py — never assign colors by page-number cycles.","pages":{str(k):v for k,v in sorted(out.items())}}
json.dump(data,open(R+'src/data/flipchart-source-colors.json','w'),ensure_ascii=False,indent=2)
open(R+'src/data/flipchart-source-colors.json','a').write('\n')
for k,v in sorted(out.items()): print(k,v)
