/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BookRouteImport } from './routes/book'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartillaIndexRouteImport } from './routes/cartilla/index'
import { Route as CartillaUnirseRouteImport } from './routes/cartilla/unirse'
import { Route as CartillaRepasoRouteImport } from './routes/cartilla/repaso'
import { Route as CartillaPracticaRouteImport } from './routes/cartilla/practica'
import { Route as CartillaMiProgresoRouteImport } from './routes/cartilla/mi-progreso'
import { Route as CartillaLibroRouteImport } from './routes/cartilla/libro'
import { Route as CartillaLeccionesRouteImport } from './routes/cartilla/lecciones'
import { Route as CartillaAutoraRouteImport } from './routes/cartilla/autora'
import { Route as CartillaTeacherIndexRouteImport } from './routes/cartilla/teacher/index'
import { Route as CartillaTeacherFlipchartRouteImport } from './routes/cartilla/teacher/flipchart'
import { Route as CartillaLeccionNRouteImport } from './routes/cartilla/leccion.$n'
import { Route as AuthenticatedCartillaTeacherRouteImport } from './routes/_authenticated/cartilla.teacher'
import { Route as CartillaTeacherFlipchartNRouteImport } from './routes/cartilla/teacher/flipchart.$n'
import { Route as AuthenticatedCartillaTeacherRemasterReviewRouteImport } from './routes/_authenticated/cartilla.teacher.remaster-review'
import { Route as AuthenticatedCartillaTeacherPresentacionRouteImport } from './routes/_authenticated/cartilla.teacher.presentacion'
import { Route as AuthenticatedCartillaTeacherBrandingRouteImport } from './routes/_authenticated/cartilla.teacher.branding'
import { Route as AuthenticatedCartillaTeacherClaseIdRouteImport } from './routes/_authenticated/cartilla.teacher.clase.$id'
import { Route as AuthenticatedCartillaTeacherAlumnoIdRouteImport } from './routes/_authenticated/cartilla.teacher.alumno.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartillaIndexRoute = CartillaIndexRouteImport.update({
  id: '/cartilla/',
  path: '/cartilla/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartillaUnirseRoute = CartillaUnirseRouteImport.update({
  id: '/cartilla/unirse',
  path: '/cartilla/unirse',
  getParentRoute: () => rootRouteImport,
} as any)
const CartillaRepasoRoute = CartillaRepasoRouteImport.update({
  id: '/cartilla/repaso',
  path: '/cartilla/repaso',
  getParentRoute: () => rootRouteImport,
} as any)
const CartillaPracticaRoute = CartillaPracticaRouteImport.update({
  id: '/cartilla/practica',
  path: '/cartilla/practica',
  getParentRoute: () => rootRouteImport,
} as any)
const CartillaMiProgresoRoute = CartillaMiProgresoRouteImport.update({
  id: '/cartilla/mi-progreso',
  path: '/cartilla/mi-progreso',
  getParentRoute: () => rootRouteImport,
} as any)
const CartillaLibroRoute = CartillaLibroRouteImport.update({
  id: '/cartilla/libro',
  path: '/cartilla/libro',
  getParentRoute: () => rootRouteImport,
} as any)
const CartillaLeccionesRoute = CartillaLeccionesRouteImport.update({
  id: '/cartilla/lecciones',
  path: '/cartilla/lecciones',
  getParentRoute: () => rootRouteImport,
} as any)
const CartillaAutoraRoute = CartillaAutoraRouteImport.update({
  id: '/cartilla/autora',
  path: '/cartilla/autora',
  getParentRoute: () => rootRouteImport,
} as any)
const CartillaTeacherIndexRoute = CartillaTeacherIndexRouteImport.update({
  id: '/cartilla/teacher/',
  path: '/cartilla/teacher/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartillaTeacherFlipchartRoute =
  CartillaTeacherFlipchartRouteImport.update({
    id: '/cartilla/teacher/flipchart',
    path: '/cartilla/teacher/flipchart',
    getParentRoute: () => rootRouteImport,
  } as any)
const CartillaLeccionNRoute = CartillaLeccionNRouteImport.update({
  id: '/cartilla/leccion/$n',
  path: '/cartilla/leccion/$n',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCartillaTeacherRoute =
  AuthenticatedCartillaTeacherRouteImport.update({
    id: '/cartilla/teacher',
    path: '/cartilla/teacher',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const CartillaTeacherFlipchartNRoute =
  CartillaTeacherFlipchartNRouteImport.update({
    id: '/$n',
    path: '/$n',
    getParentRoute: () => CartillaTeacherFlipchartRoute,
  } as any)
const AuthenticatedCartillaTeacherRemasterReviewRoute =
  AuthenticatedCartillaTeacherRemasterReviewRouteImport.update({
    id: '/remaster-review',
    path: '/remaster-review',
    getParentRoute: () => AuthenticatedCartillaTeacherRoute,
  } as any)
const AuthenticatedCartillaTeacherPresentacionRoute =
  AuthenticatedCartillaTeacherPresentacionRouteImport.update({
    id: '/presentacion',
    path: '/presentacion',
    getParentRoute: () => AuthenticatedCartillaTeacherRoute,
  } as any)
const AuthenticatedCartillaTeacherBrandingRoute =
  AuthenticatedCartillaTeacherBrandingRouteImport.update({
    id: '/branding',
    path: '/branding',
    getParentRoute: () => AuthenticatedCartillaTeacherRoute,
  } as any)
const AuthenticatedCartillaTeacherClaseIdRoute =
  AuthenticatedCartillaTeacherClaseIdRouteImport.update({
    id: '/clase/$id',
    path: '/clase/$id',
    getParentRoute: () => AuthenticatedCartillaTeacherRoute,
  } as any)
const AuthenticatedCartillaTeacherAlumnoIdRoute =
  AuthenticatedCartillaTeacherAlumnoIdRouteImport.update({
    id: '/alumno/$id',
    path: '/alumno/$id',
    getParentRoute: () => AuthenticatedCartillaTeacherRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/login': typeof LoginRoute
  '/cartilla/autora': typeof CartillaAutoraRoute
  '/cartilla/lecciones': typeof CartillaLeccionesRoute
  '/cartilla/libro': typeof CartillaLibroRoute
  '/cartilla/mi-progreso': typeof CartillaMiProgresoRoute
  '/cartilla/practica': typeof CartillaPracticaRoute
  '/cartilla/repaso': typeof CartillaRepasoRoute
  '/cartilla/unirse': typeof CartillaUnirseRoute
  '/cartilla/': typeof CartillaIndexRoute
  '/cartilla/teacher': typeof AuthenticatedCartillaTeacherRouteWithChildren
  '/cartilla/leccion/$n': typeof CartillaLeccionNRoute
  '/cartilla/teacher/flipchart': typeof CartillaTeacherFlipchartRouteWithChildren
  '/cartilla/teacher/': typeof CartillaTeacherIndexRoute
  '/cartilla/teacher/branding': typeof AuthenticatedCartillaTeacherBrandingRoute
  '/cartilla/teacher/presentacion': typeof AuthenticatedCartillaTeacherPresentacionRoute
  '/cartilla/teacher/remaster-review': typeof AuthenticatedCartillaTeacherRemasterReviewRoute
  '/cartilla/teacher/flipchart/$n': typeof CartillaTeacherFlipchartNRoute
  '/cartilla/teacher/alumno/$id': typeof AuthenticatedCartillaTeacherAlumnoIdRoute
  '/cartilla/teacher/clase/$id': typeof AuthenticatedCartillaTeacherClaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/login': typeof LoginRoute
  '/cartilla/autora': typeof CartillaAutoraRoute
  '/cartilla/lecciones': typeof CartillaLeccionesRoute
  '/cartilla/libro': typeof CartillaLibroRoute
  '/cartilla/mi-progreso': typeof CartillaMiProgresoRoute
  '/cartilla/practica': typeof CartillaPracticaRoute
  '/cartilla/repaso': typeof CartillaRepasoRoute
  '/cartilla/unirse': typeof CartillaUnirseRoute
  '/cartilla': typeof CartillaIndexRoute
  '/cartilla/teacher': typeof CartillaTeacherIndexRoute
  '/cartilla/leccion/$n': typeof CartillaLeccionNRoute
  '/cartilla/teacher/flipchart': typeof CartillaTeacherFlipchartRouteWithChildren
  '/cartilla/teacher/branding': typeof AuthenticatedCartillaTeacherBrandingRoute
  '/cartilla/teacher/presentacion': typeof AuthenticatedCartillaTeacherPresentacionRoute
  '/cartilla/teacher/remaster-review': typeof AuthenticatedCartillaTeacherRemasterReviewRoute
  '/cartilla/teacher/flipchart/$n': typeof CartillaTeacherFlipchartNRoute
  '/cartilla/teacher/alumno/$id': typeof AuthenticatedCartillaTeacherAlumnoIdRoute
  '/cartilla/teacher/clase/$id': typeof AuthenticatedCartillaTeacherClaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/book': typeof BookRoute
  '/login': typeof LoginRoute
  '/cartilla/autora': typeof CartillaAutoraRoute
  '/cartilla/lecciones': typeof CartillaLeccionesRoute
  '/cartilla/libro': typeof CartillaLibroRoute
  '/cartilla/mi-progreso': typeof CartillaMiProgresoRoute
  '/cartilla/practica': typeof CartillaPracticaRoute
  '/cartilla/repaso': typeof CartillaRepasoRoute
  '/cartilla/unirse': typeof CartillaUnirseRoute
  '/cartilla/': typeof CartillaIndexRoute
  '/_authenticated/cartilla/teacher': typeof AuthenticatedCartillaTeacherRouteWithChildren
  '/cartilla/leccion/$n': typeof CartillaLeccionNRoute
  '/cartilla/teacher/flipchart': typeof CartillaTeacherFlipchartRouteWithChildren
  '/cartilla/teacher/': typeof CartillaTeacherIndexRoute
  '/_authenticated/cartilla/teacher/branding': typeof AuthenticatedCartillaTeacherBrandingRoute
  '/_authenticated/cartilla/teacher/presentacion': typeof AuthenticatedCartillaTeacherPresentacionRoute
  '/_authenticated/cartilla/teacher/remaster-review': typeof AuthenticatedCartillaTeacherRemasterReviewRoute
  '/cartilla/teacher/flipchart/$n': typeof CartillaTeacherFlipchartNRoute
  '/_authenticated/cartilla/teacher/alumno/$id': typeof AuthenticatedCartillaTeacherAlumnoIdRoute
  '/_authenticated/cartilla/teacher/clase/$id': typeof AuthenticatedCartillaTeacherClaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/login'
    | '/cartilla/autora'
    | '/cartilla/lecciones'
    | '/cartilla/libro'
    | '/cartilla/mi-progreso'
    | '/cartilla/practica'
    | '/cartilla/repaso'
    | '/cartilla/unirse'
    | '/cartilla/'
    | '/cartilla/teacher'
    | '/cartilla/leccion/$n'
    | '/cartilla/teacher/flipchart'
    | '/cartilla/teacher/'
    | '/cartilla/teacher/branding'
    | '/cartilla/teacher/presentacion'
    | '/cartilla/teacher/remaster-review'
    | '/cartilla/teacher/flipchart/$n'
    | '/cartilla/teacher/alumno/$id'
    | '/cartilla/teacher/clase/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/login'
    | '/cartilla/autora'
    | '/cartilla/lecciones'
    | '/cartilla/libro'
    | '/cartilla/mi-progreso'
    | '/cartilla/practica'
    | '/cartilla/repaso'
    | '/cartilla/unirse'
    | '/cartilla'
    | '/cartilla/teacher'
    | '/cartilla/leccion/$n'
    | '/cartilla/teacher/flipchart'
    | '/cartilla/teacher/branding'
    | '/cartilla/teacher/presentacion'
    | '/cartilla/teacher/remaster-review'
    | '/cartilla/teacher/flipchart/$n'
    | '/cartilla/teacher/alumno/$id'
    | '/cartilla/teacher/clase/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/book'
    | '/login'
    | '/cartilla/autora'
    | '/cartilla/lecciones'
    | '/cartilla/libro'
    | '/cartilla/mi-progreso'
    | '/cartilla/practica'
    | '/cartilla/repaso'
    | '/cartilla/unirse'
    | '/cartilla/'
    | '/_authenticated/cartilla/teacher'
    | '/cartilla/leccion/$n'
    | '/cartilla/teacher/flipchart'
    | '/cartilla/teacher/'
    | '/_authenticated/cartilla/teacher/branding'
    | '/_authenticated/cartilla/teacher/presentacion'
    | '/_authenticated/cartilla/teacher/remaster-review'
    | '/cartilla/teacher/flipchart/$n'
    | '/_authenticated/cartilla/teacher/alumno/$id'
    | '/_authenticated/cartilla/teacher/clase/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  BookRoute: typeof BookRoute
  LoginRoute: typeof LoginRoute
  CartillaAutoraRoute: typeof CartillaAutoraRoute
  CartillaLeccionesRoute: typeof CartillaLeccionesRoute
  CartillaLibroRoute: typeof CartillaLibroRoute
  CartillaMiProgresoRoute: typeof CartillaMiProgresoRoute
  CartillaPracticaRoute: typeof CartillaPracticaRoute
  CartillaRepasoRoute: typeof CartillaRepasoRoute
  CartillaUnirseRoute: typeof CartillaUnirseRoute
  CartillaIndexRoute: typeof CartillaIndexRoute
  CartillaLeccionNRoute: typeof CartillaLeccionNRoute
  CartillaTeacherFlipchartRoute: typeof CartillaTeacherFlipchartRouteWithChildren
  CartillaTeacherIndexRoute: typeof CartillaTeacherIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartilla/': {
      id: '/cartilla/'
      path: '/cartilla'
      fullPath: '/cartilla/'
      preLoaderRoute: typeof CartillaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartilla/unirse': {
      id: '/cartilla/unirse'
      path: '/cartilla/unirse'
      fullPath: '/cartilla/unirse'
      preLoaderRoute: typeof CartillaUnirseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartilla/repaso': {
      id: '/cartilla/repaso'
      path: '/cartilla/repaso'
      fullPath: '/cartilla/repaso'
      preLoaderRoute: typeof CartillaRepasoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartilla/practica': {
      id: '/cartilla/practica'
      path: '/cartilla/practica'
      fullPath: '/cartilla/practica'
      preLoaderRoute: typeof CartillaPracticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartilla/mi-progreso': {
      id: '/cartilla/mi-progreso'
      path: '/cartilla/mi-progreso'
      fullPath: '/cartilla/mi-progreso'
      preLoaderRoute: typeof CartillaMiProgresoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartilla/libro': {
      id: '/cartilla/libro'
      path: '/cartilla/libro'
      fullPath: '/cartilla/libro'
      preLoaderRoute: typeof CartillaLibroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartilla/lecciones': {
      id: '/cartilla/lecciones'
      path: '/cartilla/lecciones'
      fullPath: '/cartilla/lecciones'
      preLoaderRoute: typeof CartillaLeccionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartilla/autora': {
      id: '/cartilla/autora'
      path: '/cartilla/autora'
      fullPath: '/cartilla/autora'
      preLoaderRoute: typeof CartillaAutoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartilla/teacher/': {
      id: '/cartilla/teacher/'
      path: '/cartilla/teacher'
      fullPath: '/cartilla/teacher/'
      preLoaderRoute: typeof CartillaTeacherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartilla/teacher/flipchart': {
      id: '/cartilla/teacher/flipchart'
      path: '/cartilla/teacher/flipchart'
      fullPath: '/cartilla/teacher/flipchart'
      preLoaderRoute: typeof CartillaTeacherFlipchartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartilla/leccion/$n': {
      id: '/cartilla/leccion/$n'
      path: '/cartilla/leccion/$n'
      fullPath: '/cartilla/leccion/$n'
      preLoaderRoute: typeof CartillaLeccionNRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cartilla/teacher': {
      id: '/_authenticated/cartilla/teacher'
      path: '/cartilla/teacher'
      fullPath: '/cartilla/teacher'
      preLoaderRoute: typeof AuthenticatedCartillaTeacherRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/cartilla/teacher/flipchart/$n': {
      id: '/cartilla/teacher/flipchart/$n'
      path: '/$n'
      fullPath: '/cartilla/teacher/flipchart/$n'
      preLoaderRoute: typeof CartillaTeacherFlipchartNRouteImport
      parentRoute: typeof CartillaTeacherFlipchartRoute
    }
    '/_authenticated/cartilla/teacher/remaster-review': {
      id: '/_authenticated/cartilla/teacher/remaster-review'
      path: '/remaster-review'
      fullPath: '/cartilla/teacher/remaster-review'
      preLoaderRoute: typeof AuthenticatedCartillaTeacherRemasterReviewRouteImport
      parentRoute: typeof AuthenticatedCartillaTeacherRoute
    }
    '/_authenticated/cartilla/teacher/presentacion': {
      id: '/_authenticated/cartilla/teacher/presentacion'
      path: '/presentacion'
      fullPath: '/cartilla/teacher/presentacion'
      preLoaderRoute: typeof AuthenticatedCartillaTeacherPresentacionRouteImport
      parentRoute: typeof AuthenticatedCartillaTeacherRoute
    }
    '/_authenticated/cartilla/teacher/branding': {
      id: '/_authenticated/cartilla/teacher/branding'
      path: '/branding'
      fullPath: '/cartilla/teacher/branding'
      preLoaderRoute: typeof AuthenticatedCartillaTeacherBrandingRouteImport
      parentRoute: typeof AuthenticatedCartillaTeacherRoute
    }
    '/_authenticated/cartilla/teacher/clase/$id': {
      id: '/_authenticated/cartilla/teacher/clase/$id'
      path: '/clase/$id'
      fullPath: '/cartilla/teacher/clase/$id'
      preLoaderRoute: typeof AuthenticatedCartillaTeacherClaseIdRouteImport
      parentRoute: typeof AuthenticatedCartillaTeacherRoute
    }
    '/_authenticated/cartilla/teacher/alumno/$id': {
      id: '/_authenticated/cartilla/teacher/alumno/$id'
      path: '/alumno/$id'
      fullPath: '/cartilla/teacher/alumno/$id'
      preLoaderRoute: typeof AuthenticatedCartillaTeacherAlumnoIdRouteImport
      parentRoute: typeof AuthenticatedCartillaTeacherRoute
    }
  }
}

interface AuthenticatedCartillaTeacherRouteChildren {
  AuthenticatedCartillaTeacherBrandingRoute: typeof AuthenticatedCartillaTeacherBrandingRoute
  AuthenticatedCartillaTeacherPresentacionRoute: typeof AuthenticatedCartillaTeacherPresentacionRoute
  AuthenticatedCartillaTeacherRemasterReviewRoute: typeof AuthenticatedCartillaTeacherRemasterReviewRoute
  AuthenticatedCartillaTeacherAlumnoIdRoute: typeof AuthenticatedCartillaTeacherAlumnoIdRoute
  AuthenticatedCartillaTeacherClaseIdRoute: typeof AuthenticatedCartillaTeacherClaseIdRoute
}

const AuthenticatedCartillaTeacherRouteChildren: AuthenticatedCartillaTeacherRouteChildren =
  {
    AuthenticatedCartillaTeacherBrandingRoute:
      AuthenticatedCartillaTeacherBrandingRoute,
    AuthenticatedCartillaTeacherPresentacionRoute:
      AuthenticatedCartillaTeacherPresentacionRoute,
    AuthenticatedCartillaTeacherRemasterReviewRoute:
      AuthenticatedCartillaTeacherRemasterReviewRoute,
    AuthenticatedCartillaTeacherAlumnoIdRoute:
      AuthenticatedCartillaTeacherAlumnoIdRoute,
    AuthenticatedCartillaTeacherClaseIdRoute:
      AuthenticatedCartillaTeacherClaseIdRoute,
  }

const AuthenticatedCartillaTeacherRouteWithChildren =
  AuthenticatedCartillaTeacherRoute._addFileChildren(
    AuthenticatedCartillaTeacherRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedCartillaTeacherRoute: typeof AuthenticatedCartillaTeacherRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCartillaTeacherRoute:
    AuthenticatedCartillaTeacherRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface CartillaTeacherFlipchartRouteChildren {
  CartillaTeacherFlipchartNRoute: typeof CartillaTeacherFlipchartNRoute
}

const CartillaTeacherFlipchartRouteChildren: CartillaTeacherFlipchartRouteChildren =
  {
    CartillaTeacherFlipchartNRoute: CartillaTeacherFlipchartNRoute,
  }

const CartillaTeacherFlipchartRouteWithChildren =
  CartillaTeacherFlipchartRoute._addFileChildren(
    CartillaTeacherFlipchartRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  BookRoute: BookRoute,
  LoginRoute: LoginRoute,
  CartillaAutoraRoute: CartillaAutoraRoute,
  CartillaLeccionesRoute: CartillaLeccionesRoute,
  CartillaLibroRoute: CartillaLibroRoute,
  CartillaMiProgresoRoute: CartillaMiProgresoRoute,
  CartillaPracticaRoute: CartillaPracticaRoute,
  CartillaRepasoRoute: CartillaRepasoRoute,
  CartillaUnirseRoute: CartillaUnirseRoute,
  CartillaIndexRoute: CartillaIndexRoute,
  CartillaLeccionNRoute: CartillaLeccionNRoute,
  CartillaTeacherFlipchartRoute: CartillaTeacherFlipchartRouteWithChildren,
  CartillaTeacherIndexRoute: CartillaTeacherIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
